name: Docker Backend Image CI/CD

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/lablup-webchat:backend .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lablup-webchat:backend

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Pulling backend image from Docker..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/lablup-webchat:backend
            docker stop backend || true
            docker rm backend || true
            docker run -d --log-driver=syslog -p 8080:8080 --network app-network --env-file .env --name backend ${{ secrets.DOCKER_USERNAME }}/lablup-webchat:backend
            echo "Backend Docker image has been deployed successfully."
            docker image prune -a -f
