name: Docker Frontend Image CI/CD

on:
  push:
    paths:
      - frontend/**
      - .github/workflows/deploy-frontend.yml
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/lablup-webchat:frontend .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lablup-webchat:frontend

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Pulling dashboard image from Docker..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/lablup-webchat:frontend
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --log-driver=syslog -p 3000:3000 --network app-network --env-file .env --name frontend ${{ secrets.DOCKER_USERNAME }}/lablup-webchat:frontend
            echo "Frontend docker image has been deployed successfully."
            docker image prune -a -f